version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "8080:80"  # Expose port 80 in the container as port 8080 on the host
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"    # Expose port 80 in the container as port 80 on the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
