name: Deploy to Vultr Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/my-react-app:latest .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/my-react-app:latest

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          script: |
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/my-react-app:latest
            docker stop my-react-app || true
            docker rm my-react-app || true
            docker run -d -p 80:80 --name my-react-app ghcr.io/${{ secrets.GHCR_USERNAME }}/my-react-app:latest