name: Deploy to Vultr Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: txtnvite
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/txtnvite/number-collector:latest .
          docker push ghcr.io/txtnvite/number-collector:latest

      - name: SSH Deploy to Vultr Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          passphrase: ${{ secrets.SERVER_SSH_KEY_PASSPHRASE }}
          script: |
            docker login ghcr.io -u txtnvite -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/txtnvite/number-collector:latest
            docker stop number-collector || true
            docker rm number-collector || true
            docker run -d -p 8080:80 --name number-collector ghcr.io/txtnvite/number-collector:latest
